# Generated by Django 4.2.6 on 2023-10-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller_tb',
        ),
    ]
