# Generated by Django 4.2.6 on 2023-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_seller_username_seller_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='login_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
