# Generated by Django 4.2.6 on 2023-11-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eKart_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('company_name', models.CharField(default=' ', max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('seller_picture', models.ImageField(upload_to='seller/')),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('bank_name', models.CharField(default=' ', max_length=50)),
                ('bank_branch', models.CharField(default=' ', max_length=50)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='product/')),
                ('status', models.CharField(default='available', max_length=20)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eKart_admin.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'db_table': 'product_tb',
            },
        ),
    ]
